"""create views

Revision ID: 0e075dfde276
Revises: 2bfe70811bd1
Create Date: 2020-05-02 16:27:15.663177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e075dfde276'
down_revision = '2bfe70811bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE VIEW ViewDirectory AS '
               ' SELECT TblDirectory.*, '
               ' TblMajor.majorName, '
               ' TblMajor.position AS majorPosition '
               ' FROM TblDirectory '
               ' LEFT JOIN TblMajor ON TblMajor.majorId=TblDirectory.majorId')
    op.execute('CREATE VIEW ViewArticle AS '
               ' SELECT TblArticle.*, '
               ' TblDirectory.dirName, '
               ' TblDirectory.position AS dirPosition, '
               ' TblDirectory.majorId, '
               ' TblMajor.majorName, '
               ' TblMajor.gitUrl, '
               ' TblMajor.position AS majorPosition '
               ' FROM TblArticle '
               ' LEFT JOIN TblDirectory ON TblDirectory.dirId=TblArticle.dirId '
               ' LEFT JOIN TblMajor ON TblMajor.majorId=TblDirectory.majorId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP VIEW ViewArticle')
    op.execute('DROP VIEW ViewDirectory')
    # ### end Alembic commands ###
