"""create table

Revision ID: 2bfe70811bd1
Revises: 
Create Date: 2020-03-23 15:49:50.204797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfe70811bd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TblArticle',
    sa.Column('articleId', sa.Integer(), nullable=False),
    sa.Column('articleKey', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('contentMd', sa.TEXT(), nullable=True),
    sa.Column('contentHtml', sa.TEXT(), nullable=True),
    sa.Column('dirId', sa.Integer(), nullable=True),
    sa.Column('posInDir', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('articleId'),
    sa.UniqueConstraint('articleKey')
    )
    op.create_table('TblDirectory',
    sa.Column('dirId', sa.Integer(), nullable=False),
    sa.Column('majorId', sa.Integer(), nullable=True),
    sa.Column('dirName', sa.TEXT(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('dirId')
    )
    op.create_table('TblMajor',
    sa.Column('majorId', sa.Integer(), nullable=False),
    sa.Column('majorName', sa.TEXT(), nullable=True),
    sa.Column('gitUrl', sa.TEXT(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('firstArticle', sa.TEXT(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('majorId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TblMajor')
    op.drop_table('TblDirectory')
    op.drop_table('TblArticle')
    # ### end Alembic commands ###
